---

- name: Install Red-Team lab in Azure
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
  - name: Copy Files
    get_url:
      url: "https://raw.githubusercontent.com/cyberbootcamp/lab12/master/terraform/Makefile"
      dest: ${HOME}/my_az_deployment
      mode: '0440'
      owner: 'kali'
      group: 'kali'