---

- name: Install Red-Team lab in Azure
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    labdir: "{{ lookup('env', 'LABDIR') }}"
    remotehost: "{{ lookup('env', 'REMOTEHOST') }}"
    ansible_connection: local
    ansible_python_interpreter: "{{ansible_playbook_python}}"
    packages:
      - ansible
      - jq
    directories:
      - path: ".my_vars"
      - path: "bin"
      - path: "my_proj"
      - path: "RedTeam"
      - path: "RedTeam/docker"
      - path: "RedTeam/docker/etc"
      - path: "RedTeam/docker/etc/roles"
      - path: "RedTeam/docker/webserver"
      - path: "RedTeam/docker/elasticsearch"



  tasks:

    - name: LABDIR Variables
      debug:
        var: labdir

    - name: REMOTEHOST Variables
      debug:
        var: remotehost

    - name: Ansible Host Variables
      debug:
        var: hostvars[inventory_hostname]
        #verbosity: 4

    - name: Install and Update Software
      apt:
        name: "{{ packages }}"
        state: latest
      register: result

    - debug:
        var: result
        verbosity: 2

    - name: ansible create directory
      file:
        path: "{{ item.path }}"
        owner: kali
        group: kali
        mode: 0755
        state: directory
      with_items:
        "{{ directories }}"

    - name: Copy Files
      get_url:
        url: "{{ remotehost }}/{{ item.file }}"
        dest: "{{ labdir }}/{{ item.file }}"
        mode: "{{ item.mode }}"
        owner: 'kali'
        group: 'kali'
        headers:
          Cache-Control: no-cache
      with_items:
        - { file: "Makefile", mode: "0440" }
        - { file: "my_Makefile", mode: "0440" }
        - { file: "bin/setup_az.sh", mode: "0555" }
        - { file: "bin/setup_tf.sh", mode: "0555" }
        - { file: "bin/setup_ip.sh", mode: "0555" }
        - { file: "bin/setvars.sh", mode: "0555" }
        - { file: "bin/subscribe.sh", mode: "0555" }
        - { file: "bin/jumpbox", mode: "0555" }
        - { file: "bin/dvwa-vm1", mode: "0555" }
        - { file: ".config/dummy", mode: "0555" }
        - { file: ".my_vars/dummy", mode: "0555" }
        - { file: "RedTeam/RedTeam-SG1.tf", mode: "0644" }
        - { file: "RedTeam/RedTeam-SG2.tf", mode: "0644" }
        - { file: "RedTeam/RedTeam-SG3.tf", mode: "0644" }
        - { file: "RedTeam/RedTeam-vars.tf", mode: "0644" }
        - { file: "RedTeam/cloud-init-1.txt", mode: "0644" }
        - { file: "RedTeam/cloud-init-2.txt", mode: "0644" }
        - { file: "RedTeam/loadbalancer.tf", mode: "0644" }
        - { file: "RedTeam/loadbalancer-2.tf", mode: "0644" }
        - { file: "RedTeam/main.tf", mode: "0644" }
        - { file: "RedTeam/mainv2.tf", mode: "0644" }
        - { file: "RedTeam/network-1.tf", mode: "0644" }
        - { file: "RedTeam/output.tf", mode: "0644" }
        - { file: "RedTeam/RedTeam_public_ip.tf", mode: "0644" }
        - { file: "RedTeam/setup.sh", mode: "0644" }
        - { file: "RedTeam/subnet-webtier.tf", mode: "0644" }
        - { file: "RedTeam/vm-1.tf", mode: "0644" }
        - { file: "RedTeam/vm-2.tf", mode: "0644" }
        - { file: "RedTeam/docker/Makefile", mode: "0640" }
        - { file: "RedTeam/docker/Dockerfile", mode: "0740" }
        - { file: "RedTeam/docker/etc/ansible.cfg", mode: "0644" }
        - { file: "RedTeam/docker/etc/hosts", mode: "0644" }
        - { file: "RedTeam/docker/update_ansible_cfg.sh", mode: "0750" }
        - { file: "RedTeam/docker/waitfordocker.sh", mode: "0750" }
        - { file: "RedTeam/docker/autoinstall.sh", mode: "0750" }
        - { file: "RedTeam/docker/webserver/site.yml", mode: "0650" }
        - { file: "RedTeam/docker/elasticsearch/site.yml", mode: "0650" }
