---
- name: My first playbook
  hosts: elasticsearch
  become: true
  tasks:

    - name: Install apache httpd  (state=present is optional)
      apt:
        name: apache2
        state: absent

    - name: docker.io
      apt:
        name: docker.io
        state: present

    - name: Install pip
      apt:
        name: python-pip
        state: present

    - name: Install Docker python module
      pip:
        name: docker
        state: present


    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
        pull: yes
        state: started
        published_ports: 9200:9200,9300:9300