---
- name: My first playbook
  hosts: webservers
  become: true
  tasks:

    - name: Install apache httpd  (state=present is optional)
      apt:
        name: apache2
        state: absent

    - name: docker.io
      apt:
        name: docker.io
        state: present

    - name: Install pip
      apt:
        name: python-pip
        state: present

    - name: Install Docker python module
      pip:
        name: docker
        state: present

    - name: download and launch a docker web container
      docker_container:
        name: dvwa
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80